---
- name: Add Docker apt key.
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key
    state: present
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /"
    state: present
    update_cache: true

- name: Install skopeo
  package:
    name: skopeo
    state: present
